#!/bin/sh

start() {
    printf "Starting NAA: "
    /usr/sbin/networkaudiod 2>&1 | /usr/sbin/gpio28 &
    }
stop() {
    killall -9 networkaudiod
    killall -9 gpio28
    /opt/unmute.sh
}
restart() {
	stop
	start
}
case "$1" in
  start|stop|restart)
	"$1"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
